### PR TITLE
Fixed issue where restart conversation was not clearing history.

### LINKED ISSUE #1323: Latest version of Emulator does not clear the conversation history when "Restart conversation" is clicked
## Version
4.2.142494

## Describe the bug
Emulator does not clear the conversation history when "Restart conversation" is clicked

## To Reproduce
1. Enter text into the conversation panel
2. Click on 'Restart conversation'
3. Observe that the conversation history is still present

## Screenshot

image

## Expected behavior
The conversation history should disappear

[bug]

### PR DESCRIPTION
**Pull request by tonyanziano**
Fixes #1323

### CODE REVIEW

File: packages/app/client/src/ui/editor/emulator/emulator.tsx [hunk 1]
```diff
@@ -360,18 +374,17 @@ export class EmulatorComponent extends React.Component<EmulatorProps, {}> {
         this.props.trackEvent('conversation_restart', {
           userId: 'new',
         });
-        const newUserId = uniqueIdv4();
-        // set new user as current on emulator facilities side
-        await CommandServiceImpl.remoteCall(SharedConstants.Commands.Emulator.SetCurrentUser, newUserId);
-        this.props.updateChat(this.props.documentId, { userId: newUserId });
+        // start conversation with new convo id & user id
+        this.startNewConversation(undefined, true, true);
```
Comment (compulim) [inline packages/app/client/src/ui/editor/emulator/emulator.tsx]: Why don't we create unique ID before we call `startNewConversation`? E.g. `this.startNewConversation({ ...this.props, document: { ...this.props.document, conversationId: uniqueIdv4(), userId: uniqueIdv4() } });` And can we always call `setCurrentUser` every time we call `startNewConversation`?

Your existing logic may be good or have some reasons behind, I just didn't see through it yet. If there are any, please consider me approved. 😅

Comment (tonyanziano) [reply packages/app/client/src/ui/editor/emulator/emulator.tsx]: I don't see why this approach wouldn't work. I actually like it a lot more than making a function call like `(undefined, true, true)` -- seems odd

File: packages/app/client/src/ui/editor/emulator/emulator.tsx [hunk 2]
```diff
@@ -360,18 +374,17 @@ export class EmulatorComponent extends React.Component<EmulatorProps, {}> {
...
         break;
       }
 
       case SameUserId:
         this.props.trackEvent('conversation_restart', {
           userId: 'same',
         });
-        this.startNewConversation();
+        // start conversation with new convo id
+        this.startNewConversation(undefined, true);
```
Comment (compulim) [inline packages/app/client/src/ui/editor/emulator/emulator.tsx]: Or should it be like this?

```suggestion
        this.startNewConversation(undefined, true, false);
```

File: packages/app/client/src/ui/editor/emulator/emulator.tsx (hunk 1 above)
Comment (tonyanziano) [reply packages/app/client/src/ui/editor/emulator/emulator.tsx]: I tried this approach out and it actually causes new livechat windows to be opened on every restart, as well as prevents webchat from connecting to directline when restarting with a new user id. I'm not entirely sure why though. I believe it might have to do with setting the current user every time.
