### PR TITLE
Fixes #1283 - opening a bot that has moved should show a message

### LINKED ISSUE #1283: Emulator - opening a bot that has been moved should show a message
## Version
4.2.148187 Windows and Mac

## Describe the bug
When you open a bot from My Bots or File > Open Recent ... and the .bot file cannot be found, nothing happens.

## To Reproduce
1. File > Open Recent ... or from Welcome tab, go to "My Bots".
2. Select a bot that you've deleted or moved.
3. Nothing happens.

## Expected behavior
Add a modal similar to this from VS Code:
image

[bug]

### PR DESCRIPTION
**Pull request by justinwilaby**
Fixes #1283

### CODE REVIEW

File: packages/app/main/src/commands/electronCommands.ts [hunk 1]
```diff
@@ -1,4 +1,11 @@
 //
+import * as path from 'path';
+
+import { SharedConstants } from '@bfemulator/app-shared';
+import { CommandRegistryImpl } from '@bfemulator/sdk-shared';
+import * as Electron from 'electron';
+import { app, dialog, Menu, MessageBoxOptions } from 'electron';
+import * as fs from 'fs-extra';
```
Comment (a-b-r-o-w-n) [inline packages/app/main/src/commands/electronCommands.ts]: Oops. Looks like these got move up!

File: packages/app/main/src/main.ts [hunk 2]
```diff
@@ -1,4 +1,13 @@
 //
+import * as path from 'path';
+import { setTimeout } from 'timers';
+import * as url from 'url';
+
+import { newNotification, Notification, PersistentSettings, Settings, SharedConstants } from '@bfemulator/app-shared';
+import { Users } from '@bfemulator/emulator-core';
+import { ProgressInfo } from 'builder-util-runtime';
+import { app, dialog, systemPreferences } from 'electron';
+import { UpdateInfo } from 'electron-updater';
```
Comment (a-b-r-o-w-n) [inline packages/app/main/src/main.ts]: imports got moved up here as well

File: packages/app/main/src/commands/electronCommands.ts (hunk 1 above)
Comment (justinwilaby) [reply packages/app/main/src/commands/electronCommands.ts]: Dang! I really need to get this fixed on my editor.
