### PR TITLE
[ISSUE#1397] Fix file explorer opening when clicking on HeroCard button

### LINKED ISSUE #1397: File explorer opening when clicking on HeroCard button
## Version
4.3.3
Win 10 Home  10.0.17763

## Describe the bug
When clicking on a hero card with "imBack", a file explorer is opening ("This PC"), in addition to sending the postback

## To Reproduce
this message:
```json
{
  "attachmentLayout": "carousel",
  "attachments": [
    {
      "content": {
        "buttons": [],
        "images": [
          {}
        ],
        "subtitle": "Where do you want to order from?",
        "tap": {
          "type": "showImage"
        },
        "title": "Welcome, User!"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store sajj san jose"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "4140 North First St Ste 10 San Jose CA 95134",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "sajj san jose"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store Sajj Mountain View"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "2580 West El Camino Real #4 Mountain View, CA 94040",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "Sajj Mountain View"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store Sajj Sunnyvale"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "145 S Frances ST Sunnyvale, CA 94086",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "Sajj Sunnyvale"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store sajj menlo park"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "883 Hamilton Ave, Menlo Park, CA 94025",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "sajj menlo park"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store sajj san francisco"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "636 2nd Street, San Francisco, CA 94107",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "sajj san francisco"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store sajj rancho santa margarita"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "22245 El Paseo, Suite A, Rancho Santa Margarita, CA 92688",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "sajj rancho santa margarita"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    },
    {
      "content": {
        "buttons": [
          {
            "text": "Select this store",
            "title": "Select this store",
            "type": "imBack",
            "value": "Select store sajj san jose"
          }
        ],
        "images": [
          {
            "url": ""
          }
        ],
        "subtitle": "4140 North First St Ste 10 San Jose CA 95134",
        "tap": {
          "type": "showImage",
          "value": ""
        },
        "title": "sajj san jose"
      },
      "contentType": "application/vnd.microsoft.card.hero"
    }
  ],
  "channelId": "emulator",
  "conversation": {
    "id": "c5f4a830-5072-11e9-8d51-6ba1c40e95ee|livechat"
  },
  "entities": [],
  "from": {
    "id": "cf446530-43d2-11e9-b7f8-a571966de5c1",
    "name": "Bot",
    "role": "bot"
  },
  "id": "5cad8e90-5073-11e9-8dd7-d732260bde0b",
  "localTimestamp": "2019-03-27T11:33:21+02:00",
  "locale": "",
  "recipient": {
    "id": "61309d57-169b-4858-ab31-a740e0c92b6c",
    "role": "user"
  },
  "replyToId": "1b684470-5073-11e9-8dd7-d732260bde0b",
  "serviceUrl": "http://localhost:2175",
  "showInInspector": true,
  "suggestedActions": {
    "actions": [
      {
        "title": "Send Location",
        "type": "imBack",
        "value": "Send Location"
      }
    ]
  },
  "text": "Choose from the carousel, Enter a Zip Code, city, or send your location.",
  "timestamp": "2019-03-27T09:33:21.785Z",
  "type": "message"
}
```

click on "select this store" will open file explorer (in addition for sending the postback to the bot)

## Expected behavior
only send postback to the bot

[bug]

### PR DESCRIPTION
**Pull request by denscollo**
Fixes #1397 

# Description
Added validation to check the value of the URL before using it because if it's empty, the file explorer will open by default.

# Specific changes
- Add URL validation when hyperlink is open

# Testing
We used the user hero card to test the fix. 
image

### CODE REVIEW

File: packages/app/client/src/interceptHyperlink.ts [hunk 1]
```diff
@@ -52,6 +52,8 @@ export default function interceptHyperlink() {
 
   // Monkey patch window.open
   window.open = (url: string): any => {
```
Comment (justinwilaby) [inline packages/app/client/src/interceptHyperlink.ts]: There is nothing wrong with this approach however, I'm confident this logic should be reviewed for incorporation into [WebChat at this location](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Middleware/CardAction/createCoreMiddleware.js#L34). It seems like an enhancement that could have value there.

**Comment by justinwilaby** [comment]
This is related to [#1504](https://github.com/microsoft/BotFramework-WebChat/issues/1504) and [#368](https://github.com/microsoft/BotFramework-WebChat/issues/368) in webchat.

@cwhitten - can you please provide definitive guidance on an action item here? Although not ideal, we can adopt this PR as an interim solution until a WebChat solution is available or I can work with @compulim and @corinagum to revive [#1604](https://github.com/microsoft/BotFramework-WebChat/pull/1604)

**Comment by cwhitten** [comment]
The window.open ponyfill in WebChat landed [here](https://github.com/microsoft/BotFramework-WebChat/pull/1704).

**Comment by justinwilaby** [comment]
I'm seeing that just now. It looks like we want to implement the `cardActionMiddleware` in the Emulator and then perform the checks when a URL is opened.

**Comment by denscollo** [comment]
@justinwilaby @cwhitten thanks for the feedback! We'll be working by using the example and let you know as soon as we have the new solution.

**Comment by Bill7zz** [comment]
@justinwilaby feedback applied

**Comment by cwhitten** [comment]
@denscollo is this ready for review? At the moment we're seeing an extremely small diff.

**Comment by tonyanziano** [comment]
@denscollo I believe what Justin meant by using that example, is that we want to implement the `cardActionMiddleware` in the Emulator and then pass it into the Web Chat component as a prop when [we render it here.](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx#L109)

So it would look something like:

**chat.tsx**

```
const cardActionMiddleware = () => next => async ({ cardAction, getSignInUrl }) => {
  // your fix
};

public render() {

  <ReactWebChat
    cardActionMiddleware={cardActionMiddleware}
    ...
  />
```

**Comment by justinwilaby** [comment]
Thank you for providing this clarification @tonyanziano

**Comment by denscollo** [comment]
@justinwilaby @tonyanziano Thanks for the clarification! This is still a WIP, we are working on it. We are reviewing the changes on our fork and then we'll push them.

**Comment by denscollo** [comment]
@justinwilaby @tonyanziano the PR is now ready for review!

File: packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx [hunk 2]
```diff
@@ -140,6 +141,31 @@ export class Chat extends Component<ChatProps, ChatState> {
...
+        const url = await getSignInUrl();
+        popup.location.href = url;
+        break;
+
+      case 'downloadFile':
+      case 'playAudio':
+      case 'playVideo':
+      case 'showImage':
+      case 'openUrl':
+        if (confirm(`Do you want to open this URL?\n\n${value}`)) {
```
Comment (justinwilaby) [inline packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx]: We typically favor custom dialogs over native since UX continuity is better across the app. Also, `confirm` is thread-blocking and may have side-effects if the main process sends IPC messages during the display of this confirmation modal.

I realize this is more work to create a custom prompt using the `DialogService` but I believe it's the right thing to do. Please feel free to reach out to me if you need guidance on implementing this.

**Comment by denscollo** [comment]
@justinwilaby Ok, we'll be working on this approach and let you know if we have doubts. Thanks!

**Comment by denscollo** [comment]
@justinwilaby we finished applying the feedback, so it's ready for review!

File: packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx [hunk 3]
```diff
@@ -140,6 +142,34 @@ export class Chat extends Component<ChatProps, ChatState> {
...
+        const url = await getSignInUrl();
+        popup.location.href = url;
+        break;
+      }
+      case 'downloadFile':
+      case 'playAudio':
+      case 'playVideo':
+      case 'showImage':
+      case 'openUrl':
+        this.props.showOpenUrlDialog(value).then(result => {
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx]: I think that there should be validation here to check if the url (`value`) is not empty before prompting the user. 

ex:

```
case 'openUrl':
  if (!value) {
    return / break;
  }
```

I pulled down your branch and used the card payload included in the original issue, and clicking on one of the card buttons showed the url dialog, but still opened the file explorer once I hit confirm.

I believe the desired behavior is for the file explorer not to open in this case.

> Expected behavior
only send postback to the bot
