### PR TITLE
Fixed #1196 - post to new conversation does not work

### LINKED ISSUE #1196: POST /v3/conversations ➡ InternalServerError: Cannot read property 'appid' of undefined
## Version
4.2.1

## Describe the bug
Bot Framework emulator is throwing a `500 InternalServerError` when posting to `/v3/conversations`, despite the same code works in a deployed bot with Microsoft Teams.

(1) The error message is `Cannot read property 'appid' of undefined`, when the request contains a valid JWT Bearer token in the Authorization header. (The JWT payload DOES contain a property called `appid` btw.)

(2) If I leave the Authorization header empty, I get another `500 InternalServerError` and the error message is `Cannot read property 'payload' of undefined`. 

(3) If I send some random text as the Bearer token in the Authorization header - as suggested [here](https://github.com/Microsoft/BotFramework-Emulator/issues/706) - I get a `401 Unauthorized` (at least not another `500 InternalServerError` 🙄).

## Repro steps
1. Start the Bot Framework Emulator.
2. Open Postman.
3. Make a POST request to the local `serviceUrl`'s `/v3/conversations` endpoint (it should look like this: `http://localhost:PORT/v3/conversations`) with the request body included below and (1) a JWT generated by the .NET Bot Builder SDK v4 / (2) nothing / (3) some random text in the Authorization header.
4. See error.

## Expected behavior
- DO NOT give back `500 InternalServerErrors` with JavaScript error messages on the API endpoints. Handle the errors and send back a `400 BadRequest` or even an `500 InternalServerError` but with a meaningful error message.
- In the (1) situation the API should respond with a `200 OK` and send the `conversationId` in the body of the response.
- In the (2) situation the API should respond with a `401 Unauthorized` IMHO, but clearly not with `500 InternalServerError`.
- In the (3) situation the `401 Unauthorized` is correct IMHO, but if we take @tonyanziano's [comment](https://github.com/Microsoft/BotFramework-Emulator/issues/706#issuecomment-449051197) into account, then it should respond correctly with `200 OK` and a `conversationId`.

## Debug
I was able trace the issue back to this line in the Bot Framework Emulator: https://github.com/Microsoft/BotFramework-Emulator/blob/4b620e3367938243a70fada026654280727b7beb/packages/emulator/core/src/conversations/middleware/getBotEndpoint.ts#L64
But I'm not totally sure what is causing the issue here. Maybe something is broken in JWT parsing.

## Additional context
Request body:
``` json
{
  "bot": {
    "id": "3",
    "name": "Bot",
    "role": "bot"
  },
  "members": [
    {
      "id": "3570b2c3-9377-4880-87a1-666bba16d0bb",
      "name": "User",
      "role": "user"
    }
  ],
  "channelData": {
    "clientActivityId": "1545857215036.8654911430483678.2"
  }
}
```

Parsed JWT token:
``` jwt
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "nbCwW56w3KsB-xUaPlLOSLjODGQ",
  "kid": "nbCwW56w3KsB-xUaPlLOSLjODGQ"
}.{
  "aud": "https://api.botframework.com",
  "iss": "https://sts.windows.net/d6d49420-****-****-****-************/",
  "iat": 1545856906,
  "nbf": 1545856906,
  "exp": 1545860806,
  "aio": "42RgPOsZXnazy/hiHcpsJAVW1petAA==",
  "appid": "3e58d71d-****-****-****-************",
  "appidacr": "1",
  "idp": "https://sts.windows.net/d6d49420-****-****-****-************/",
  "tid": "d6d49420-****-****-****-************",
  "uti": "pL3r9YTz7EuFksrQefLsAA",
  "ver": "1.0"
}.[Signature]
```

Code used to make the request originally with the .NET Bot Builder SDK v4:
``` csharp
await _botFrameworkAdapter.CreateConversationAsync(
    "emulator",
    "http://localhost:31973",
    new MicrosoftAppCredentials(**appId**, **appPassword**),
    new ConversationParameters(bot: **botChannelAccount**, members: new List<ChannelAccount> { **userChannelAccount** }, channelData: **channelData**),
    Callback(),
    cancellationToken);
```

[bug]

### PR DESCRIPTION
**Pull request by justinwilaby**
This PR fixes #1196 by resolving 500s received when posting to `/v3/conversations` and by opening a new live chat window upon successfully posting.

### CODE REVIEW

File: packages/app/main/src/restServer.ts [hunk 1]
```diff
@@ -55,101 +68,104 @@ export class RestServer {
...
+        `${ facility }.${ routeName }`
+      ),
+    );
+  }
+
+  private onNewConversation = async (conversation: Conversation) => {
+    if (!conversation ||
+      !conversation.conversationId ||
+      !conversation.conversationId.length ||
+      conversation.conversationId.includes('transcript')) {
```
Comment (a-b-r-o-w-n) [inline packages/app/main/src/restServer.ts]: This should be extracted into a method since the logic is shared between `onRouterAfter` and here.

File: packages/app/main/src/restServer.ts [hunk 2]
```diff
@@ -55,101 +68,104 @@ export class RestServer {
...
+      return;
+    }
+    // Check for an existing livechat window
+    // before creating a new one since "new"
+    // can also mean "restart".
+    let { conversationId } = conversation;
+    if (!conversationId.includes('livechat') &&
+      !this.botEmulator.facilities.conversations.conversationById(conversationId + '|livechat')) {
```
Comment (a-b-r-o-w-n) [inline packages/app/main/src/restServer.ts]: I think this could be improved with a method extraction as well.

File: packages/emulator/core/src/conversations/middleware/createConversation.ts [hunk 3]
```diff
@@ -37,99 +37,94 @@ import * as Restify from 'restify';
...
+    // for (let key in conversationParameters.members) {
+    //   newUsers.push({
+    //     id: conversationParameters.members[key].id,
+    //     name: conversationParameters.members[key].name
+    //   });
+    // }
+    // getStore().dispatch({
+    //   type: "Users_AddUsers",
+    //   state: { users: newUsers }
+    // });
```
Comment (a-b-r-o-w-n) [inline packages/emulator/core/src/conversations/middleware/createConversation.ts]: Can this be removed?

File: packages/emulator/core/src/conversations/middleware/createConversation.ts [hunk 4]
```diff
@@ -37,99 +37,94 @@ import * as Restify from 'restify';
...
+    } else if (!conversationParameters.bot) {
+      error = ErrorCodes.MissingProperty;
+      errorMessage = 'The "Bot" parameter is required';
+    } else if (conversationParameters.bot.id !== botEndpoint.botId) {
+      error = ErrorCodes.BadArgument;
+      errorMessage = 'conversationParameters.bot.id doesn\'t match security bot id';
+    } else if (!botEndpoint) {
+      error = ErrorCodes.MissingProperty;
+      errorMessage = 'The Emulator only supports bot-created conversation with AppID-bearing bot';
+    }
```
Comment (a-b-r-o-w-n) [inline packages/emulator/core/src/conversations/middleware/createConversation.ts]: This is should be extracted to another method and improved for readability. I find myself getting lost in the chained conditions and get distracted from all of the other things this method already does.

Comment (justinwilaby) [reply packages/emulator/core/src/conversations/middleware/createConversation.ts]: i should probably just revert to the existing implementation since it wasn't related to the fix. This was a fast fix for `throw` being caught locally which existed previously.

Comment (a-b-r-o-w-n) [reply packages/emulator/core/src/conversations/middleware/createConversation.ts]: I think it is a positive change, it could just be taken a bit further.

File: packages/emulator/core/src/types/errorCodes.ts [hunk 5]
```diff
@@ -31,21 +31,19 @@
 // WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 //
 
-class ErrorCodes {
+export enum ErrorCodes {
```
Comment (a-b-r-o-w-n) [inline packages/emulator/core/src/types/errorCodes.ts]: :+1:
