### PR TITLE
Fixed the spinner issue when publishing LUIS after training

### LINKED ISSUE #1572: Publish to LUIS UI hangs with a loading spinner
from @gabog 

## Version
4.4.1

## Describe the bug

Training works fine in the extension when I add a new intent but publish stays spinning after a click it. The model does publish but the UI never turns off the spinning animation.

## To Reproduce
1. Get the LUIS extension rendered on a LUIS trace
2. Train and publish to the model
4. See scrolling

## Expected behavior
Upon success, the spinning animation should go away.

## Screenshots
thumbnail_image001

[bug]

### PR DESCRIPTION
**Pull request by ivanov-dan**
fixes #1572

### CODE REVIEW

File: packages/extensions/luis/client/src/App.tsx [hunk 1]
```diff
@@ -321,7 +321,7 @@ export class App extends Component<any, AppState> {
       $host.logger.error(err.message);
       $host.trackEvent('luis_publishFailure', { error: err.message });
     } finally {
-      $host.setAccessoryState(TrainAccessoryId, AccessoryDefaultState);
+      $host.setAccessoryState(PublishAccessoryId, AccessoryDefaultState);
```
Comment (justinwilaby) [inline packages/extensions/luis/client/src/App.tsx]: So this was the crux of the fix?

Comment (tonyanziano) [reply packages/extensions/luis/client/src/App.tsx]: Looks like it was resetting the state of the train button instead of the publish button?

Comment (ivanov-dan) [reply packages/extensions/luis/client/src/App.tsx]: Yes, that was it.
