### PR TITLE
[#1741] Restore focus after dialog has been closed

### LINKED ISSUE #1741: [MAS3.2.1][Keyboard Navigation-Sign in with your azure account] When the user press the enter key on “Sign in with your azure account” focus is not the dialog controls
**Actual Result:**
When the user press the enter key on “Sign in with your azure account” focus is not the dialog controls after press tab key focus is moves to the somewhere i.e design guidelines link.

**Expected Result:**
When the user press the enter key on“Sign in with your azure account” focus should be lands on the dialog control only after press the tab key focus should moves to the next interactive control i.e “Don’t have an azure account? sign up.”

**Note:** Same issue exits throughout the application  for all dialog controls 
Same issue repro for below path
Navigate to the Open bot ->Select the Open bot control->Open bot dialog
Welcome Bot Framework Emulator ->Create new bot configuration
Navigate to the Open bot ->Select the Open bot control->Open bot dialog ->Connect the bot 
Bot Explorer->Services->+symbol
Bot Explorer->Services->+symbol->Add language understanding

**Repro Steps:**
1.Open the Bot Framework V4 Emulator.
2.Navigate to the Welcome tab screen
3.Navigate to the sign in with your azure account and select it 
4.Dialog gest opened and try to navigate dialog using tab key 
5.Observe the issue

**User Impact:**
Users who rely on keyboard navigation will be affected to navigate the control if keyboard focus is not lands on the expected control keyboard users will be affected.

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a4bbd37d-ee11-485e-b5c8-0539f0ac94b2}](url)
[MAS3.2.1_Sign in  with your account.zip](https://github.com/microsoft/BotFramework-Emulator/files/3515089/MAS3.2.1_Sign.in.with.your.account.zip)

### PR DESCRIPTION
**Pull request by corinagum**
#1741 

maintainFocus

Previous fix to this bug did not return focus to the component that opened the dialog. 

Now the focus should be restored after closing the dialog.

### CODE REVIEW

File: packages/app/client/src/commands/uiCommands.ts [hunk 1]
```diff
@@ -176,14 +176,17 @@ export class UiCommands {
...
-    store.dispatch(
-      beginAzureAuthWorkflow(
-        AzureLoginPromptDialogContainer,
-        { serviceType },
-        AzureLoginSuccessDialogContainer,
-        AzureLoginFailedDialogContainer
-      )
-    );
+    return new Promise(async resolve => {
+      await store.dispatch(
```
Comment (tonyanziano) [inline packages/app/client/src/commands/uiCommands.ts]: `dispatch()` is not an asynchronous function so you don't need to use `await` or `async` here

File: packages/app/client/src/state/actions/connectedServiceActions.ts [hunk 2]
```diff
@@ -108,11 +112,15 @@ export function openContextMenuForConnectedService<T>(
 }
 
 export function openAddServiceContextMenu(
-  payload: ConnectedServicePickerPayload
-): ConnectedServiceAction<ConnectedServicePickerPayload> {
+  payload: ConnectedServicePickerPayload,
+  resolver: () => void
```
Comment (tonyanziano) [inline packages/app/client/src/state/actions/connectedServiceActions.ts]: In the other files you defined the type of `resolver` as `Function`. To maintain consistency change this type to `Function` or change the other types to `() => void`

File: packages/app/client/src/state/sagas/endpointSagas.spec.ts [hunk 3]
```diff
@@ -99,20 +106,79 @@ jest.mock('electron', () => ({
...
+  it('should launch an endpoint editor', () => {
+    const gen = EndpointSagas.launchEndpointEditor(endpointServiceAction);
+    gen.next();
+    gen.next([endpointService]);
+    expect(gen.next().done).toBe(true);
+    expect(resolver).toHaveBeenCalledTimes(1);
+    expect(mockRemoteCommandsCalled.length).toEqual(1);
+  });
+
+  // OLD TESTS
```
Comment (tonyanziano) [inline packages/app/client/src/state/sagas/endpointSagas.spec.ts]: necessary?

File: packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx [hunk 4]
```diff
@@ -136,8 +145,36 @@ export class WelcomePage extends React.Component<WelcomePageProps, {}> {
     this.props.switchToBot(bot.path);
   };
 
-  private onOpenBotClick = () => {
-    this.props.showOpenBotDialog();
+  private onOpenBotClick = async () => {
+    const { openBotButtonRef } = this;
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx]: unnecessary extra line since this isn't being reused anywhere in the function, `this.openBotButtonRef.focus()` should be fine below

File: packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx [hunk 5]
```diff
@@ -136,8 +145,36 @@ export class WelcomePage extends React.Component<WelcomePageProps, {}> {
...
+    await this.props.showOpenBotDialog();
+
+    openBotButtonRef.focus();
+  };
+
+  private onNewBotClickPromise = async () => {
+    const { newBotButtonRef } = this;
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx]: unnecessary extra line since this isn't being reused anywhere in the function, `this.newBotButtonRef.focus()` should be fine below

File: packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx [hunk 6]
```diff
@@ -136,8 +145,36 @@ export class WelcomePage extends React.Component<WelcomePageProps, {}> {
...
+    await this.props.onNewBotClick();
+
+    newBotButtonRef.focus();
+  };
+
+  private signInToAzurePromise = async () => {
+    const { signIntoAzureButtonRef } = this;
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx]: unnecessary extra line since this isn't being reused anywhere in the function, `this.signIntoAzureButtonRef.focus()` should be fine below

File: packages/app/client/src/ui/shell/explorer/botExplorerBar/botExplorerBar.tsx [hunk 7]
```diff
@@ -79,4 +82,15 @@ export default class BotExplorerBar extends React.Component<BotExplorerBarProps,
       </div>
     );
   }
+
+  private openBotSettingsClick = async () => {
+    const { openBotSettingsButtonRef } = this;
```
Comment (tonyanziano) [inline packages/app/client/src/ui/shell/explorer/botExplorerBar/botExplorerBar.tsx]: unnecessary extra line since this isn't being reused anywhere in the function, `this.openBotSettingsButtonRef.focus()` should be fine below

File: packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.tsx [hunk 8]
```diff
@@ -69,10 +75,17 @@ export class BotNotOpenExplorer extends React.Component<BotNotOpenExplorerProps,
   }
 
   private onCreateNewBotClick = async () => {
-    this.props.showCreateNewBotDialog();
+    const { createNewBotButtonRef } = this;
```
Comment (tonyanziano) [inline packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.tsx]: unnecessary extra line since this isn't being reused anywhere in the function, `this.createNewBotButtonRef.focus()` should be fine below

File: packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss [hunk 9]
```diff
@@ -84,3 +84,8 @@ ul.kv-pair-container {
   position: absolute;
   top: -9999px;
 }
+
+
+.kv-spacing {
+  margin-right: 15px;
+}
```
Comment (tonyanziano) [inline packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss]: newline

File: packages/sdk/ui-react/src/widget/button/linkButton.tsx [hunk 10]
```diff
@@ -49,18 +50,29 @@ export interface LinkButtonProps extends React.ButtonHTMLAttributes<HTMLButtonEl
...
         {this.props.children}
       </button>
     );
   }
+
+  private setButtonRef = (ref: HTMLButtonElement): void => {
+    const { buttonRef } = this.props;
+    buttonRef && buttonRef(ref);
+  };
 }
```
Comment (tonyanziano) [inline packages/sdk/ui-react/src/widget/button/linkButton.tsx]: Add tests for this component

File: packages/sdk/ui-react/src/widget/button/primaryButton.tsx [hunk 11]
```diff
@@ -35,18 +35,24 @@ import * as React from 'react';
...
         {text}
         {this.props.children}
       </button>
     );
   }
+
+  private setButtonRef = (ref: HTMLButtonElement): void => {
+    const { buttonRef } = this.props;
+    buttonRef && buttonRef(ref);
+  };
```
Comment (tonyanziano) [inline packages/sdk/ui-react/src/widget/button/primaryButton.tsx]: Add a test for this

File: packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx [hunk 12]
```diff
@@ -136,8 +145,36 @@ export class WelcomePage extends React.Component<WelcomePageProps, {}> {
     this.props.switchToBot(bot.path);
   };
 
-  private onOpenBotClick = () => {
-    this.props.showOpenBotDialog();
+  private onOpenBotClick = async () => {
+    const { openBotButtonRef } = this;
+    await this.props.showOpenBotDialog();
+
+    openBotButtonRef.focus();
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx]: Might want to guard against undefined or falsy references to button refs:

`openBotButtonref && openBotButtonRef.focus()`

and apply this pattern to other instances of this behavior.

File: packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx [hunk 13]
```diff
@@ -136,8 +145,36 @@ export class WelcomePage extends React.Component<WelcomePageProps, {}> {
...
+  };
+
+  private onNewBotClickPromise = async () => {
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx]: can remove `Promise` from the function name, we don't use that pattern anywhere else

File: packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx [hunk 14]
```diff
@@ -136,8 +145,36 @@ export class WelcomePage extends React.Component<WelcomePageProps, {}> {
...
+    const { newBotButtonRef } = this;
+    await this.props.onNewBotClick();
+
+    newBotButtonRef.focus();
+  };
+
+  private signInToAzurePromise = async () => {
```
Comment (tonyanziano) [inline packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx]: can remove `Promise` from the function name, we don't use that pattern anywhere else

**Comment by corinagum** [comment]
@tonyanziano ping, tests went up!
