### PR TITLE
Data url links will now prompt to save to disk.

### LINKED ISSUE #1130: Download link opens Windows Store and fails to download
_From @paulio on August 8, 2018 15:19_

Create an embedded text document launches the Windows Store rather than download the file
``` 
var contentType = "text/plain";
var attachment = new Attachment
{
    Name = "Transcript.txt",
    ContentUrl = $"data:{contentType};base64,{Convert.ToBase64String(bytes)}",
    ContentType = contentType
};
```

_Copied from original issue: Microsoft/BotFramework-Emulator#752_

### PR DESCRIPTION
**Pull request by tonyanziano**
Fixes #1130 

===

image

### CODE REVIEW

File: packages/app/client/src/hyperlinkHandler.ts [hunk 1]
```diff
@@ -50,7 +50,16 @@ export function navigate(url: string) {
...
     } else {
       CommandServiceImpl.remoteCall(TrackEvent, 'app_openLink', { url }).catch(_e => void 0);
-      shell.openExternal(url, { activate: true });
+      // manually create and click a download link for data url's
+      if (url.startsWith('data:')) {
+        const a = document.createElement('a');
+        a.href = url;
+        a.download = '';
+        a.click();
+        a.remove();
```
Comment (justinwilaby) [inline packages/app/client/src/hyperlinkHandler.ts]: This is inconsequential since the element is never being added to the dom. It can probably be removed.

Comment (tonyanziano) [reply packages/app/client/src/hyperlinkHandler.ts]: remove the remove?!?

Comment (tonyanziano) [reply packages/app/client/src/hyperlinkHandler.ts]: I'll change it when I inevitably have to update the branch once the azure gov fix goes into master.
